baseURL = "/"
languageCode = "en_US"
title = "Brendan Ryan"
theme = "hugo-initio"
pluralizeListTitles = false

[params]
    name = "Brendan Ryan"
    description = "At the intersection of technology and liberal arts"
    email = ""
    phone = ""
    address = ""
    year = ""
    avatar = "images/brendanryan.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head.png"
    favicon = "images/favicon.icon"
    DateForm = ""
    author = "Brendan Ryan"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "bio"
    url = "/bio/"
    weight = 2
[[menu.main]]
    name = "RePi"
    url = "/RePi/"
    weight = 3
#[[menu.main]]
#    name = "posts"
#    url = "/posts/"
#    weight = 5

#[params.disqus]
#    site = "hugo-initio-site.disqus.com"

#[params.sharethis]
#    property = "123456789012345678901234"
#    custom = true

#[params.google.analytics]
#    trackerID = "GA-000000000-0"

#[[params.social]]
#	title = "facebook"
#	url = "https://www.facebook.com/nickname"
#    icon = "fab fa-facebook-square"
#    footer = true
#    sharethis = true
#    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/bcmryan"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
#[[params.social]]
#	title = "instagram"
#	url = "https://www.instagram.com/nickname"
#    icon = "fab fa-instagram"
#    footer = true
#    sharethis = false
#    network = ""
#[[params.social]]
#	title = "google+"
#	url = "https://plus.google.com/+nickname"
#    icon = "fab fa-google-plus-square"
#    footer = false
#    sharethis = true
#    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/bcmryan"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
#[[params.social]]
#	title = "tumblr"
#	url = "https://nickname.tumblr.com"
#    icon = "fab fa-tumblr-square"
#    footer = false
#    sharethis = false
#    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/bcmryan"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:bcm.ryan@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = false
    network = "email"
